server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pharmacy_auth
    username: root
    password: pharmacy123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/