server:
  port: 8083

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          

      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: drug-service
          uri: lb://drug-service
          predicates:
            - Path=/drugs/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka